"""
Symptom entity lexicon organized by pathological domain.
This list includes variations of symptom and disease-related expressions
commonly found in biomedical literature discussing polyphenols.
"""

KNOWN_SYMPTOMS = set([
    "aging",
    "alzheimer's disease",
    "apoptosis",
    "atherosclerosis",
    "bone loss",
    "brain aging",
    "breast cancer",
    "cancer",
    "carcinogenesis",
    "cardiomyopathy",
    "cell damage",
    "cell death",
    "chronic pain",
    "cognitive decline",
    "colorectal cancer",
    "dementia",
    "dna damage",
    "dyslipidemia",
    "endothelial dysfunction",
    "fatigue",
    "fever",
    "glucose intolerance",
    "gut dysbiosis",
    "heart failure",
    "hepatotoxicity",
    "high blood pressure",
    "hyperglycemia",
    "hyperlipidemia",
    "hypertension",
    "impaired autophagy",
    "inflammation",
    "inflammatory bowel disease",
    "insulin resistance",
    "joint inflammation",
    "leukemia",
    "liver damage",
    "liver fibrosis",
    "liver injury",
    "metabolic syndrome",
    "memory impairment",
    "mitochondrial dysfunction",
    "muscle atrophy",
    "neurodegeneration",
    "neuroinflammation",
    "obesity",
    "osteoporosis",
    "oxidative damage",
    "oxidative phosphorylation failure",
    "oxidative stress",
    "pain",
    "parkinson's disease",
    "premature aging",
    "proteostasis imbalance",
    "rheumatoid arthritis",
    "skeletal muscle loss",
    "steatosis",
    "stress",
    "tumor growth",
    "tumor progression",
    "type 2 diabetes",
    "vascular inflammation"
])
